#light
(*
-----------------------------------------------------------------------------
Project Euler Problem #44
http://projecteuler.net/index.php?section=problems&id=44
-----------------------------------------------------------------------------
  
Pentagonal numbers are generated by the formula, P_(n)=n(3n−1)/2. The first 
ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_(4) + P_(7) = 22 + 70 = 92 = P_(8). However, their 
difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_(j) and P_(k), for which their sum and 
difference is pentagonal and D = |P_(k)− P_(j)| is minimised; what is the 
value of D?

Answer:
-----------------------------------------------------------------------------
*)

module Problem44

open System

let RunA _ =
    Display.Print "Solution #1 Result"

let RunB _ =
    Display.Print "Solution #2 Result"

let public Solutions = [RunA;RunB]

  